---
title: "WOPINS Sexuality Analysis"
output: 
  html_document:
    df_print: paged
    theme: lumen
    highlight: haddock
    toc: yes
    toc_float: yes
    code_fold: show
    self_contained: true
---

<style>
body {
text-align: justify}
</style>

```{r}

# set the defaults for the codechunks
knitr::opts_chunk$set( eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE )

```

```{r setup}

# ----------
# Setup 

# Clear the workspace
rm( list = ls() )

# libraries
library( here ) # for calling local directory
library( dplyr ) # for working with the data
library( network ) # for creating the network object
library( sna ) # for working with the network
library( ergm ) # for erg models
library( pander ) # for tables


# run the script to create the networks with the attributes
source( here( "WOPINS-sexuality-BUILD.R" ) )


```

```{r define-friend-model}

# ----------
# ERGMs

# build function with formula for ergm
net.formula <- function( net, gwideg.val, gwesp.val ){
  net.terms <- 
    ( net ~ edges 
      
      # structural terms
      + mutual 
      + twopath
      + gwidegree( gwideg.val, fixed=TRUE )
      + gwesp( gwesp.val, fixed = TRUE )
      
      # terms of interest
      + nodeifactor( "sex_minority" )
      + nodeofactor( "sex_minority" )
      + nodematch( "sex_minority" )
      + nodeicov( "prismom" )
      + nodeocov( "prismom" )
      + nodematch( "prismom" )
      + nodeicov( "sexacceptance_reverse" )
      + nodeocov( "sexacceptance_reverse" )
      + absdiff( "sexacceptance_reverse" )
      
      #controls
      + nodeicov( "age" )
      + nodeocov( "age" )
      + nodeicov( "grade" )
      + nodeocov( "grade" )
      + nodeicov( "white" )
      + nodeocov( "white" )
      + nodeicov( "unitdays100" )
      + nodeocov( "unitdays100" )
      + nodeicov( "protestantbinary" )
      + nodeocov( "protestantbinary" )
      + nodeicov( "healthchangefrom3mopre" )
      + nodeocov( "healthchangefrom3mopre" )
      + nodeicov( "MentalPhysicalHealth" )
      + nodeocov( "MentalPhysicalHealth" )
      + nodeicov( "SocialIntegration" )
      + nodeocov( "SocialIntegration" )
      + nodeicov( "timealone" )
      + nodeocov( "timealone" )
    )
  
  net.fit <- ergm( net.terms, 
                   control = control.ergm(
                     seed        = 601601,
                     MCMLE.maxit = 1000 ) )
  return( net.fit )
  
}

```

## Models of Friendship

### Unit 2 Model

```{r unit-2-f-model}

# estimate the model
u2.model <- net.formula( u2.net, gwideg.val = 1.50, gwesp.val = 0.75 )

# run the model for unit 2
summary( u2.model )

```

----

### Unit 3 Model

```{r unit-3-f-model}

# estimate the model
u3.model <- net.formula( u3.net, gwideg.val = 1.25, gwesp.val = 1.00 )

# run the model for unit 3
summary( u3.model )

```


### Pooled Model

```{r pooled-f-model}
  
pooled.formula <- 
    ( u2.u3.pooled.net ~ edges 
      
      # structural terms
      + mutual
      + twopath
      + gwidegree( 0.75, fixed=TRUE )
      + gwesp( 1.25, fixed = TRUE )
      
      # terms of interest
      + nodeifactor( "sex_minority" )
      + nodeofactor( "sex_minority" )
      + nodematch( "sex_minority" )
      + nodeicov( "prismom" )
      + nodeocov( "prismom" )
      + nodematch( "prismom" )
      + nodeicov( "sexacceptance_reverse" )
      + nodeocov( "sexacceptance_reverse" )
      + absdiff( "sexacceptance_reverse" )
      
      #controls
      + nodeicov( "age" )
      + nodeocov( "age" )
      + nodeicov( "grade" )
      + nodeocov( "grade" )
      + nodeicov( "white" )
      + nodeocov( "white" )
      + nodeicov( "unitdays100" )
      + nodeocov( "unitdays100" )
      + nodeicov( "protestantbinary" )
      + nodeocov( "protestantbinary" )
      + nodeicov( "healthchangefrom3mopre" )
      + nodeocov( "healthchangefrom3mopre" )
      + nodeicov( "MentalPhysicalHealth" )
      + nodeocov( "MentalPhysicalHealth" )
      + nodeicov( "SocialIntegration" )
      + nodeocov( "SocialIntegration" )
      + nodeicov( "timealone" )
      + nodeocov( "timealone" )

)
  
set.seed( 601601 )
pooled.fit <- ergm( 
  pooled.formula, 
  constraints = ~ blocks( "block", levels2 = c( 2, 3 ) ) 
  )

summary( pooled.fit )

```

----

## Models of Power/Influence

### Unit 2 Model

```{r unit-2-p-model}

# estimate the model
u2.p.model <- net.formula( u2.p.net, gwideg.val = 1.50, gwesp.val = 0.75 )

# run the model for unit 2
summary( u2.p.model )

```

----

### Unit 3 Model

```{r unit-3-p-model}

# estimate the model
u3.p.model <- net.formula( u3.p.net, gwideg.val = 1.25, gwesp.val = 1.00 )

# run the model for unit 3
summary( u3.p.model )

```



### Pooled Model

```{r pooled-p-model}
  
pooled.formula <- 
    ( u2.u3.p.pooled.net ~ edges 
      
      # structural terms
      + mutual
      + twopath
      + gwidegree( 0.75, fixed=TRUE )
      + gwesp( 1.25, fixed = TRUE )
      
      # terms of interest
      + nodeifactor( "sex_minority" )
      + nodeofactor( "sex_minority" )
      + nodematch( "sex_minority" )
      + nodeicov( "prismom" )
      + nodeocov( "prismom" )
      + nodematch( "prismom" )
      + nodeicov( "sexacceptance_reverse" )
      + nodeocov( "sexacceptance_reverse" )
      + absdiff( "sexacceptance_reverse" )
      
      #controls
      + nodeicov( "age" )
      + nodeocov( "age" )
      + nodeicov( "grade" )
      + nodeocov( "grade" )
      + nodeicov( "white" )
      + nodeocov( "white" )
      + nodeicov( "unitdays100" )
      + nodeocov( "unitdays100" )
      + nodeicov( "protestantbinary" )
      + nodeocov( "protestantbinary" )
      + nodeicov( "healthchangefrom3mopre" )
      + nodeocov( "healthchangefrom3mopre" )
      + nodeicov( "MentalPhysicalHealth" )
      + nodeocov( "MentalPhysicalHealth" )
      + nodeicov( "SocialIntegration" )
      + nodeocov( "SocialIntegration" )
      + nodeicov( "timealone" )
      + nodeocov( "timealone" )
      
      # Terms to test
      + S(
        ~ nodeifactor( "sex_minority" ) 
        + nodeofactor( "sex_minority" ) 
        + nodematch( "sex_minority" )
        + nodeicov( "sexacceptance_reverse" ) 
        + nodeocov( "sexacceptance_reverse" ) 
        + absdiff( "sexacceptance_reverse" ),
        ~ ( block == 1 )
        )

)
  
set.seed( 601601 )
pooled.p.fit <- ergm( 
  pooled.formula, 
  constraints = ~ blocks( "block", levels2 = c( 2, 3 ) ) 
  )

summary( pooled.p.fit )

```


<br>
<br>

###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***