---
title: "WOPINS Sexuality BIC Analysis"
output: 
  html_document:
    df_print: paged
    theme: lumen
    highlight: haddock
    toc: yes
    toc_float: yes
    code_fold: show
    self_contained: true
---

<style>
body {
text-align: justify}
</style>

```{r setup-chunk, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

# ----------
# Setup 

# Clear the workspace
rm( list = ls() )

# libraries
library( here ) # for calling local directory
library( dplyr ) # for working with the data
library( network ) # for creating the network object
library( sna ) # for working with the network
library( ergm ) # for erg models
library( pander ) # for tables


# run the script to create the networks with the attributes
source( here( "WOPINS-sexuality-BUILD.R" ) )

```

This file reports the results for various BIC values for the structural terms.

```{r build-functions}

# ----
# Build the functions.

eval.bic <- function( net, I, E ){
  model.bics <- matrix( 0, nrow = length( I ), ncol = length( E ) )
  
  for ( i in 1:length( I ) ){
    for ( j in 1:length( E ) ){
      model.bics[i,j] <- 
        summary( ergm( net ~ edges
                     + mutual + twopath 
                     + gwidegree( decay = I[i], fixed = TRUE )
                     + gwesp( E[j], fixed = TRUE ) ) )$bic
    }
  }
  
  colnames( model.bics ) <- paste("I @", as.character( I ) )
  rownames( model.bics ) <- paste("E @", as.character( E ) )
  
  return( model.bics )
}

```

```{r estimate-models}

# Set the range of values to examine
I <- seq(0, 1.5, by = .05 )
E <- seq(0, 1.5, by = .05 )

# Set the seed to reproduce results.
set.seed( 12345 )

# Estimate the models
bic.u2   <- eval.bic( u2.net  , I, E )
bic.u3   <- eval.bic( u3.net  , I, E )
bic.u2.p <- eval.bic( u2.p.net, I, E )
bic.u3.p <- eval.bic( u3.p.net, I, E )

```

```{r plot-results, echo=TRUE}

# plot the BICs based on the model terms
par( mfrow = c( 2, 2 ) )
plot( bic.u2[1:nrow( bic.u2 ),], bic.u2[,1:ncol( bic.u2 )], type="b", main="BIC for GW terms (u2)", xlab = "gwindegree", ylab = "gwesp")
plot( bic.u3[1:nrow( bic.u3 ),], bic.u3[,1:ncol( bic.u3 )], type="b", main="BIC for GW terms (u3)", xlab = "gwindegree", ylab = "gwesp")
plot( bic.u2.p[1:nrow( bic.u2.p ),], bic.u2.p[,1:ncol( bic.u2.p )], type="b", main="BIC for GW terms (u2.p)", xlab = "gwindegree", ylab = "gwesp")
plot( bic.u3.p[1:nrow( bic.u3.p ),], bic.u3.p[,1:ncol( bic.u3.p )], type="b", main="BIC for GW terms (u3.p)", xlab = "gwindegree", ylab = "gwesp")
par( mfrow = c( 1, 1 ) )

# find the minimums
min( bic.u2 )
min( bic.u3 )
min( bic.u2.p )
min( bic.u3.p )

```

<br>
<br>

###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***